<a href="https://colab.research.google.com/github/m9ts/AD-temp-inst/blob/main/TrabalhoII_temp_inst.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [174]:
!git clone https://github.com/m9ts/AD-temp-inst.git

fatal: destination path 'AD-temp-inst' already exists and is not an empty directory.

In [175]:
path = "/content/drive/MyDrive/AD/Atividade_II/database_temp_inst.csv"

In [176]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler, MinMaxScaler, OneHotEncoder
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier

In [177]:
pd.set_option('display.float_format','{:.2f}'.format)

In [178]:
df_temp_inst = pd.read_csv(path, sep = ';')

In [179]:
df_temp_inst.head(10)

,data,hora,pressao,radiacao,temp_inst,pto_orvalho_inst,umid_inst,vento_vel,Unnamed: 8
0,2013-12-03,0,949.30,-3.54,22.30,21.00,92.00,2.30,NaN
1,2013-12-03,100,949.70,-3.54,22.10,20.60,91.00,2.10,NaN
2,2013-12-03,200,949.40,-3.54,22.10,20.00,88.00,1.30,NaN
3,2013-12-03,300,949.10,-3.54,21.90,20.20,90.00,2.30,NaN
4,2013-12-03,400,948.60,-3.54,21.40,19.80,91.00,1.50,NaN
5,2013-12-03,500,947.80,-3.54,21.20,19.80,92.00,2.00,NaN
6,2013-12-03,600,947.30,-3.54,20.80,19.40,92.00,1.80,NaN
7,2013-12-03,700,947.70,-3.54,20.40,19.60,95.00,1.70,NaN
8,2013-12-03,800,948.30,-3.44,20.40,19.70,95.00,1.80,NaN
9,2013-12-03,900,949.20,38.05,20.60,19.80,95.00,1.90,NaN

In [180]:
print(f'O dataset possui {df_temp_inst.shape[0]} entradas e {df_temp_inst.shape[1]} variáveis.')
print(f'Os tipos de dados são:\n{df_temp_inst.dtypes}')

O dataset possui 83232 entradas e 9 variáveis.
Os tipos de dados são:
data                 object
hora                  int64
pressao             float64
radiacao            float64
temp_inst           float64
pto_orvalho_inst    float64
umid_inst           float64
vento_vel           float64
Unnamed: 8          float64
dtype: object

In [181]:
df_temp_inst.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 83232 entries, 0 to 83231
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   data              83232 non-null  object
 1   hora              83232 non-null  int64
 2   pressao           77953 non-null  float64
 3   radiacao          77953 non-null  float64
 4   temp_inst         77953 non-null  float64
 5   pto_orvalho_inst  77948 non-null  float64
 6   umid_inst         77947 non-null  float64
 7   vento_vel         77953 non-null  float64
 8   Unnamed: 8        0 non-null      float64
dtypes: float64(7), int64(1), object(1)
memory usage: 5.7+ MB

In [182]:
# Coluna "Unnamed: 8" removida do dataset
df_temp_inst = df_temp_inst.drop('Unnamed: 8', axis=1)

In [186]:
df_temp_inst

,data,hora,pressao,radiacao,temp_inst,pto_orvalho_inst,umid_inst,vento_vel
0,2013-12-03,0,949.30,-3.54,22.30,21.00,92.00,2.30
1,2013-12-03,100,949.70,-3.54,22.10,20.60,91.00,2.10
2,2013-12-03,200,949.40,-3.54,22.10,20.00,88.00,1.30
3,2013-12-03,300,949.10,-3.54,21.90,20.20,90.00,2.30
4,2013-12-03,400,948.60,-3.54,21.40,19.80,91.00,1.50
...,...,...,...,...,...,...,...,...
83227,2023-06-01,1900,954.20,1195.46,24.90,15.80,57.00,1.60
83228,2023-06-01,2000,954.50,462.95,23.10,15.80,64.00,0.80
83229,2023-06-01,2100,954.70,8.56,20.00,15.40,75.00,1.20
83230,2023-06-01,2200,955.20,-3.54,19.30,15.40,78.00,1.30
83231,2023-06-01,2300,955.40,-3.54,18.60,15.10,80.00,1.50

In [183]:
df_temp_inst

,data,hora,pressao,radiacao,temp_inst,pto_orvalho_inst,umid_inst,vento_vel
0,2013-12-03,0,949.30,-3.54,22.30,21.00,92.00,2.30
1,2013-12-03,100,949.70,-3.54,22.10,20.60,91.00,2.10
2,2013-12-03,200,949.40,-3.54,22.10,20.00,88.00,1.30
3,2013-12-03,300,949.10,-3.54,21.90,20.20,90.00,2.30
4,2013-12-03,400,948.60,-3.54,21.40,19.80,91.00,1.50
...,...,...,...,...,...,...,...,...
83227,2023-06-01,1900,954.20,1195.46,24.90,15.80,57.00,1.60
83228,2023-06-01,2000,954.50,462.95,23.10,15.80,64.00,0.80
83229,2023-06-01,2100,954.70,8.56,20.00,15.40,75.00,1.20
83230,2023-06-01,2200,955.20,-3.54,19.30,15.40,78.00,1.30
83231,2023-06-01,2300,955.40,-3.54,18.60,15.10,80.00,1.50

In [185]:
# Dados faltantes
print(f'As variáveis com mais dados faltantes, em porcentagem(%), são:\n')
((df_temp_inst.isnull().sum() / df_temp_inst.shape[0])*100).sort_values(ascending=False)

As variáveis com mais dados faltantes, em porcentagem(%), são:

umid_inst          6.35
pto_orvalho_inst   6.35
radiacao           6.34
pressao            6.34
temp_inst          6.34
vento_vel          6.34
data               0.00
hora               0.00
dtype: float64

In [189]:
# Checando tipos de 'data' e 'hora'
df_temp_inst[['data', 'hora']].dtypes

data    object
hora     int64
dtype: object

In [192]:
# Convertendo a variável 'data' para o tipo DateTime
df_temp_inst['data'] = pd.to_datetime(df_temp_inst['data'])

In [194]:
# Convertendo colunas 'data' e 'hora' e criando nova coluna 'data_hora' (DateTime)
df_temp_inst['hora'] = df_temp_inst['hora'].astype(str).str.zfill(4)

df_temp_inst['data_hora'] = pd.to_datetime(
    df_temp_inst['data'].dt.strftime('%Y-%m-%d') + ' ' + df_temp_inst['hora'],
    format = '%Y-%m-%d %H%M'
)

In [197]:
df_temp_inst[['data_hora']]

                data_hora
0     2013-12-03 00:00:00
1     2013-12-03 01:00:00
2     2013-12-03 02:00:00
3     2013-12-03 03:00:00
4     2013-12-03 04:00:00
...                   ...
83227 2023-06-01 19:00:00
83228 2023-06-01 20:00:00
83229 2023-06-01 21:00:00
83230 2023-06-01 22:00:00
83231 2023-06-01 23:00:00

[83232 rows x 1 columns]

In [198]:
df_temp_inst

,data,hora,pressao,radiacao,temp_inst,pto_orvalho_inst,umid_inst,vento_vel,data_hora
0,2013-12-03,0000,949.30,-3.54,22.30,21.00,92.00,2.30,2013-12-03 00:00:00
1,2013-12-03,0100,949.70,-3.54,22.10,20.60,91.00,2.10,2013-12-03 01:00:00
2,2013-12-03,0200,949.40,-3.54,22.10,20.00,88.00,1.30,2013-12-03 02:00:00
3,2013-12-03,0300,949.10,-3.54,21.90,20.20,90.00,2.30,2013-12-03 03:00:00
4,2013-12-03,0400,948.60,-3.54,21.40,19.80,91.00,1.50,2013-12-03 04:00:00
...,...,...,...,...,...,...,...,...,...
83227,2023-06-01,1900,954.20,1195.46,24.90,15.80,57.00,1.60,2023-06-01 19:00:00
83228,2023-06-01,2000,954.50,462.95,23.10,15.80,64.00,0.80,2023-06-01 20:00:00
83229,2023-06-01,2100,954.70,8.56,20.00,15.40,75.00,1.20,2023-06-01 21:00:00
83230,2023-06-01,2200,955.20,-3.54,19.30,15.40,78.00,1.30,2023-06-01 22:00:00
83231,2023-06-01,2300,955.40,-3.54,18.60,15.10,80.00,1.50,2023-06-01 23:00:00

In [199]:
# Definindo métricas de tempo
df_temp_inst['ano'] = df_temp_inst['data_hora'].dt.year
df_temp_inst['mes'] = df_temp_inst['data_hora'].dt.month
df_temp_inst['dia'] = df_temp_inst['data_hora'].dt.day
df_temp_inst['hora_num'] = df_temp_inst['data_hora'].dt.hour
df_temp_inst['dia_semana'] = df_temp_inst['data_hora'].dt.dayofweek

In [203]:
df_temp_inst[['ano', 'mes', 'dia', 'hora_num', 'dia_semana']].head(10)

    ano  mes  dia  hora_num  dia_semana
0  2013   12    3         0           1
1  2013   12    3         1           1
2  2013   12    3         2           1
3  2013   12    3         3           1
4  2013   12    3         4           1
5  2013   12    3         5           1
6  2013   12    3         6           1
7  2013   12    3         7           1
8  2013   12    3         8           1
9  2013   12    3         9           1